package org.example.debriefrepository.types.enums;

/* to put enum in the end */
public enum RankEnum {
    PRIVATE,
    PRIVATE_FIRST_CLASS,
    CORPORAL,
    SERGEANT,
    STAFF_SERGEANT,
    SERGEANT_FIRST_CLASS,
    MASTER_SERGEANT,
    SENIOR_MASTER_SERGEANT,
    ADVANCED_MASTER, _SERGEANT,
    CHIEF_WARRANT_OFFICER,
    SECOND_LIEUTENANT,
    LIEUTENANT,
    CAPTAIN,
    MAJOR,
    LIEUTENANT_COLONEL,
    COLONEL,
    BRIGADIER_GENERAL,
    MAJOR_GENERAL,
    CHIEF_OF_STAFF
}
